[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.35.1"
async-trait = "0.1.81"
bytes = "1.6.0"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
